version: "3.8"
services:
  # Service 1: The Application
  web:
    build: .
    ports:
     - "5000:5000"
    depends_on:
      redis:
        condition: service_healthy # SENIOR TWIST: Wait for Redis to be healthy
    networks:
      - app-network

  # Service 2: The Database
  redis:
    image: "redis:alpine"
    networks:
      - app-network
    # SENIOR TWIST: Healthcheck ensures the DB is actually ready
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  # Service 3: The Load Balancer/Proxy
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro # Mount config file
    ports:
      - "80:80" # Map Host port 80 to Container port 80
    depends_on:
      - web
    networks:
      - app-network

networks:
  app-network:
    driver: bridge